language: r
cache: packages
matrix:
  include:
    - os: linux
      sudo: false
      env:
        - R_CODECOV=true
    - os: osx
      latex: false
r_packages:
  - covr
after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
